spring:
  application:
    name: fixora-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fixora_db}
    username: ${DB_USER:fixora_user}
    password: ${DB_PASSWORD:fixora_password}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
